<h1>Algorithms Reference Book</h1>
<h2>A personal reference to accompany the <a href="https://www.manning.com/books/grokking-algorithms"> Grokking Algorithms textbook</a></h2>
This jupyter notebook serves a reference to the Grokking Algorithms illustrated guide, and lays out examples of the algorithms discussed within its text, demonstrated in Python. The intended purpose is to be a helpful guide for myself and others to refer too for revision. A bit like a cheatsheet. I would highly recommend the mentioned book, and here I will expand upon it by providing python examples, and discusing additional resources for the advanced topics that are touched upon in the final chapter.

I won't be talking about data structures much here, but they are vital to good algorithm design. Data structures are covered heavily in the text, but for more info see:
* <a href="https://www.youtube.com/watch?v=NptnmWvkbTw">Arrays</a>
* <a href="https://www.youtube.com/watch?v=_jQhALI4ujg">Linked lists</a>
* <a href="https://www.youtube.com/watch?v=FNZ5o9S9prU">Stacks</a>
* <a href="https://www.youtube.com/watch?v=shs0KM3wKv8">Hash Tables</a>

I will be covering trees and heaps later on because they are not covered in the text, and I would like to expand on my own understanding.

<h3>Big O Notation</h3>
First some quick notes on Big O Notation:
* Algorithm speed isn't measured in time, but in terms of **growth** of an algorithm
* Algorithm times are written in Big O Notation
* Big O establishes a worst-case run time
* Common Big O Notations:
    * O(log n) - known as log time, example: Binary Search
    * O(n) - known as linear time, example: Simple Search
    * O(n * log n) - an example would be a fast sorting algorithm like quicksort
    * O(n^2) - an example would be a slow sorting algorithm like selection sort
    * O(n!) - n factorial, this is a really slow algorithm, like with the travelling salesperson problem
* For more examples, see http://bigocheatsheet.com/ or https://www.youtube.com/watch?v=v4cd1O4zkGw

<h3>Binary Search</h3>
If you have a sorted array, binary search provides a rapid means of searching its contents. 
* Much faster than simple search (serial search)
* Worst case scenario binary search is O(log n) wheras simple search is O(n) i.e. in the worst case scenario you will have to search through every element
* Binary search ONLY works on **sorted** arrays

In [11]:
def binary_search(array, query):
    start = 0
    finish = len(array) - 1
    while start <= finish:
        mid = start + finish
        guess = array[mid]
        if guess == query:
            return mid
        if guess > query:
            finish = mid - 1
        else:
            start = mid + 1
    return None #If the item doesn't exist, return none

In [7]:
alpha_list = ["apple", "bananna", "chips", "coconut", "grapes", "peanuts", "watermelon"]
num_list = [2,5,11,23,43,56,89,124,254]

In [8]:
binary_search(alpha_list, "chips")

2

In [9]:
binary_search(num_list, 43)

4

<h3>Selection Sort</h3>
This algorithm can be used for sorting elements by size, and the principle is that you find the smallest/largest element, and then add this element to a new list, and then repeat. The problem is this is very slow. You have to find each element, which takes O(n) time, and then add that element to a new list, which also takes O(n) time. This algorithm will therefore take O(n^2) time to complete. The example below is sorting a list from smallest to largest.

In [55]:
unsorted_numbers = [3,76,23,245,63,12,46,9,5,245,32,46,30,22,55,312]

In [15]:
def find_smallest(array):
    smallest = array[0]
    smallest_idx = 0
    for i in range(1, len(array)):
        if array[i] < smallest:
            smallest = array[i]
            smallest_idx = i
    return smallest_idx

In [16]:
def selection_sort(array):
    new_array = []
    for i in range(len(array)):
        smallest = find_smallest(array)
        new_array.append(array.pop(smallest))
    return new_array

In [17]:
selection_sort(unsorted_numbers)

[3, 5, 9, 12, 22, 23, 30, 32, 46, 46, 55, 63, 76, 245, 245, 312]

<h3>Recursion</h3>
A function that calls itself, this is the essence of recursion. When writing a recursive algorithm, you need to establish two cases:
* The base case: this is what your intended goal is, and when it returns true you stop recursion
* The recursive case: the condition in which the function will call itself
Using recursion requires understanding stacks, in particular call stacks, and this is covered very neatly in the aforementioned book, otherwise you can google it, as there are lots of great explanations.

Recursion doesn't provide any performance benefits but makes for neater and similier code. It is also an important concept used by other algorithms, for example quicksort which will be discussed later.

Recursion also comes with a cost, as each function call is added to the stack and is therefore taking up memory. If the stack gets too tall, you might need to rewrite the code as loops or use tail recursion.

I will now produce the first 10 elements of the fibonacci sequence using loops and then with recursion to demonstrate the difference.

In [43]:
#Fibonacci with loops 

x = 0
y = 1
for i in range(10):
    print(y)
    old_x = x
    x = y
    y = old_x + y

1
1
2
3
5
8
13
21
34
55


In [33]:
def fib(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n-1)+fib(n-2)

In [40]:
for i in range(10):
    print(fib(i))

0
1
1
2
3
5
8
13
21
34


A couple of more examples from the exercises in the book:

In [48]:
def sum_array(array):
    if array == []:
        return 0
    else:
        return array[0] + sum(array[1:])

In [49]:
nums = [2,64,2,3]
sum_array(nums)

71

In [46]:
def length(array):
    if array == []:
        return 0
    else:
        return 1 + length(array[1:])

In [47]:
a = ["a","b","c","d","e"]
length(a)

5

<h3>QuickSort</h3>
This is a sorting algorithm that is much faster than selection sort, and uses recursion to achieve its processing. First we chose a base case; what is the easiest array we could sort, which is an array containing only a single element. Then we make our recursion case, which involves chosing a **pivot**, which is a point where we divide the array into two, and then we call the quicksort algorithm on the two sub-arrays.

Some extra notes:
* Choose a random element as the pivot
* The average runtime is O(n log n)
* Use the divide an conquer strategy when developing algorithms with recursion. Find the base case, this is the simpiliest case to solve, and then use recursion to get to the base case

In [57]:
from random import randint

def quicksort(array):
    if len(array) < 2:
        return array
    else:
        pivot = array[randint(0, len(array)-1)]
        less = [i for i in array[1:] if i <= pivot]
        greater = [i for i in array[1:] if i > pivot]
        return quicksort(less) + [pivot] + quicksort(greater)

In [58]:
quicksort(unsorted_numbers)

[5, 5, 9, 22, 30, 32, 32, 46, 55, 55, 55, 63, 245, 245, 245, 312]

<h3>Closure</h3>
Closures are awesome! I used them previously in the UTI data project you can find in my github. The principle is that you define a function that returns a function, and the funtion is stored along with its enviroment and captured variables. This mean, that when you call the function later on you can access these captured variables even though they are outside the current scope.

Below is the example that can be found on <a href="https://en.wikipedia.org/wiki/Closure_(computer_programming)">this</a> wikipedia entry. 

In [81]:
def start(x):
    def increment_by(y):
        return x + y
    return increment_by
#The value 10 is stored within x, that is 
closure = start(10)
closure(5)

15

<h3>Breadth-first search</h3>
Breadth-first search algorithms are used for finding if a path exists, and the shortest possible path in an unweighted graph. The function below is an implementation of breadth-first search in python.

In [ ]:
# %load breadth_first.py

import collections

def search(start_point, query_function, graph):
    """Params:
        start_point: starting node, must be an existing key in graph
        query_function: function to pass search queries, must return boolean value
        graph: graph to search. Expects hash table datatype"""
    queue = collections.deque()
    queue += graph[start_point]
    searched = []

    while queue:
        query = queue.popleft()
        if not query in searched:
            if query_function(query):
                print("Matching node found!")
                return {"query_node": query, "path": searched}
        else:
            queue += graph[query]
            searched.append(query)
    return False


Notes on breadth first search:
* Tells you if there is a path from A to B
* If a path exists, it will find the shortest path
* When relating to distance, try modeling a problem as a graph
* A directed graph has arrows, and the relationship follows the arrows
* Undirected graphs don't have arrows and the relationship goes both ways
* Queues are FIFO (first in first out)
* Stacks are LIFO (last in first out)
* When doing breadth first, use a queue, need to check objects in the order they were added to the search list, otherwise you won't get the shortest path
* Make sure not to check objects twice, or else you will get an infinite loop

<h3>Dijkstra's Algorithm</h3>
Dijkstra's (pronounced deyek-stra) algorithm is for finding the shortest possible path in weighted directed acyclic graphs. NOTE: Dijkstra's algorithm does not work on graphs with negative weighted edges. See the Bellman-ford algorithm.

In [ ]:
# %load Dijkstras_Algorithm.py
class Dijkstra:
    def __init__(self, graph):
        """Initialise Dijkstra search.
        Params:
            Graph: should be a nested dictionary detailing nodes, neighbours
            and weights for edges connecting nodes and neighbours"""
        if istype(graph) is dict:
            self.graph = graph
        else:
            print("Graph of invalid datatype")
            break
        self.infinity = float("inf")

    def init_costs(self, start_node):
        #We only know the costs for the neighbours of the starting node
        #Set all other nodes to infinity
        costs = {}
        for node in self.graph:
            if node == start_node:
                for k, v in node.items():
                    costs[k] = v
            else:
                for k, v in node:
                    costs[k] = self.infinity
        return costs

    def init_parents(self, start_node):
        #Set the parent of neighbours to start node
        parents = {}
        for k, v in self.graph[start_node].items():
            parents[k] = "start"
        return parents

    def find_lowest_cost_node(self, costs, processed_nodes):
        lowest_cost = float("inf")
        lowest_cost_node = None
        for node in costs:
            cost = costs[node]
            if cost < lowest_cost_node and node not in processed_nodes:
                lowest_cost = cost
                lowest_cost_node = node
        return lowest_cost_node

    def find_shortest_path(self, start_node):
        costs = self.init_costs(start_node)
        parents = self.parents(start_node)
        processed = []
        node = self.find_lowest_cost_node(costs, processed)

        while node is not None:
            cost = costs[node]
            neighbours = self.graph[node]
            for n in neighbours.keys():
                new_cost = cost + neighbours[n]
                if costs[n] > new_cost:
                    costs[n] = new_cost
                    parents[n] = node
            processed.append(node)
            node = find_lowest_cost_node(costs, processed)
        return parents, costs


Notes on Dijkstra's Algorithm:
* Breadth-first search is used to calculate the shortest path for an unweighted graph
* Dijkstra's algorithm is used to calculate the shortest path for a weighted graph
* Dijkstra's algorithm only works when all weights are positive, otherwise use Bellman-Ford algorithm

<h3>Greedy Algorithms</h3>
Sometime's you cannot solve an algorithm for the general optimal solution, and so you want to create an algorithm that is just good enough, but is also quick. This is where greedy algorithms come into play. Greedy algorithms aim to give an approximation to the optimal solution whilst also being fast.

<h4>The Set-covering Problem</h4>
Say for example: you have a radio show and you want to reach listeners in all 50 of the US states. You need to decide what stations to play on to reach all those listeners. It costs money to be on each station so you want to minimise the number of stations you play on but get the biggest outreach possible.

You could list every possible subset of stations (the power set) and pick the set with the smallest number of stations that covers all 50 states, but there would be a total of 2^n possible subsets, and this could take a long time to calculate. So it would be better to use a greedy algorithm that approximates a reasonible answer. We can do this by picking a station that covers most of the states that haven't been covered yet (even if it overlaps with some other stations in regards to states that have been covered) and then repat until we have coverage over every state


In [5]:
#Setup
states_needed = set(["mt", "wa", "or", "id", "nv", "ut"])
stations = {
    "kone": set(["id", "nv", "ut"]),
    "ktwo": set(["wa", "id", "mt"]),
    "kthree": set(["or", "nv", "ca"]),
    "kfour": set(["nv", "ut"]),
    "kfive": set(["ca", "az"])
}
final_stations = []

In [6]:
while states_needed:
    best_station = None
    states_covered = set()
    for station, states in stations.items():
        covered = states_needed & states #This is called set intersection, see below!
        if len(covered) > len(states_covered):
            best_station = station
            states_covered = covered
    states_needed -= states_covered
    final_stations.append(best_station)

In [7]:
final_stations

['kone', 'ktwo', 'kthree']

**Set union/intersection/difference**

In [8]:
set_one = set([1,3,5,8,19,25,34])
set_two = set([1,3,15,19,23,25,42,68])    

In [9]:
#Set union
set_one | set_two

{1, 3, 5, 8, 15, 19, 23, 25, 34, 42, 68}

In [10]:
#Set intersection
set_one & set_two

{1, 3, 19, 25}

In [11]:
#Set difference
set_one - set_two

{5, 8, 34}

<h4>NP-Complete Problems</h4>

The problem above is very similar to the 'travelling salesperson' problem. The optimal solution involves calculating every possible solution and picking the smallest/shortest one. Problems like this are called NP-complete problems. (Btw, NP stands for "nondeterministic polynomial time").

As soon as you realise that a problem is an NP-problem, you should stop trying to solve it perfectly, and instead focus your efforts on making a good approximation. There is no easy way of telling if a probelm is NP-complete, but here are some giveaways:
* Your algorithm is quick when processing a few items, but soon deterioates when you add more items
* "All combinations of X" usually points to an NP-complete problem
* You can't break something down into sub-problems and so you have to calculate "every possible version of X".
* The problem involves a sequence and is difficult to solve (such as the travelling salesperson)
* If the problem involves a set and is difficult to solve (like the set-covering problem)
* If you can restate the problem like it is the travelling salesperson problem or the set-covering problem, then it is definitely NP-complete

Notes on Greedy Algorithms:
* They optimise locally, hoping to end up with a global optimum
* NP-complete problems have no known fast solution
* If you have an NP-complete problem, your best bet is to use an approximation algorithm
* Greedy algorithms are simple and fast to run, so they make for good approximation algorithms

<h3>Dynamic Programming</h3>
The process of dynamic programming involves breaking up a task into subproblems whose solutons can be used to solve a larger problem. Dynamic programming is useful when you're trying to optimize something given a constrant. For example, if you need too fit a certain number of goods of different values in a storage unit, and you are constrained by the weight of the goods, but you want to optimize the value stored.

Some important notes about dynamic programming:
* You can use dynamic programming only when the problem can be broken down into discrete subproblems, and these subproblems do not depend upon one another
* Every dynamic programming solution involves a grid
* The values in the cells of this grid are usually what you're trying to optimize
* Each cell is a subproblem, so think about how you can divide your problem into subproblems, and this will help you figure out what the axes are

An example of dynamic programming is seeing if two words are similar to one another based on common substrings. Say someone mispelt 'fish' as 'hish' and you want to see if it is closer to the word 'fish' or 'vista', then you can use dynamic programming to determine which contains the longest common substring.

In [59]:
#Longest common substring - if the letters match, take the value of the top left cell and add one
import numpy as np
def longest_com_substring(word_a, word_b):
    grid = np.zeros((len(word_a), len(word_b)))
    for i in range(0, len(word_a)):
        for j in range(0, len(word_b)):
            if word_a[i] == word_b[j]:
                grid[i][j] = grid[i-1][j-1] + 1
            else:
                grid[i][j] = 0
    print(grid)

In [60]:
word_a = "fish"
word_b = "hish"
longest_com_substring(word_a, word_b)

[[ 0.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  2.  0.]
 [ 1.  0.  0.  3.]]


In [61]:
word_a = "hish"
word_b = "vista"
longest_com_substring(word_a, word_b)

[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  2.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


But say instead of looking for the longest common substring, you wanted to know how many letters the two words have in common; the longest common subsequence. For this you would use a similar but slightly adapted method. The words "fosh" for example has the same longest common substring for both "fish" and "fort", but has more matching letters with "fist".

In [62]:
word_a = "fosh"
word_b = "fish"
longest_com_substring(word_a, word_b)

[[ 1.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  2.]]


In [63]:
word_a = "fosh"
word_b = "fort"
longest_com_substring(word_a, word_b)

[[ 1.  0.  0.  0.]
 [ 0.  2.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [64]:
#Longest common subsequence - if the letters match, take the value of the top left cell and add one, if they don't match
#take the largest value from either the left or from above
def longest_com_subseq(word_a, word_b):
    grid = np.zeros((len(word_a), len(word_b)))
    for i in range(0, len(word_a)):
        for j in range(0, len(word_b)):
            if word_a[i] == word_b[j]:
                grid[i][j] = grid[i-1][j-1] + 1
            else:
                grid[i][j] = max(grid[i-1][j], grid[i][j-1])
    print(grid)

In [66]:
word_a = "fosh"
word_b = "fish"
longest_com_subseq(word_a, word_b)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  2.  2.]
 [ 1.  1.  2.  3.]]


In [67]:
word_a = "fosh"
word_b = "fort"
longest_com_subseq(word_a, word_b)

[[ 1.  1.  1.  1.]
 [ 1.  2.  2.  2.]
 [ 1.  2.  2.  2.]
 [ 1.  2.  2.  2.]]


In [68]:
word_a = "blues"
word_b = "clues"
longest_com_subseq(word_a, word_b)

[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.]
 [ 0.  1.  2.  2.  2.]
 [ 0.  1.  2.  3.  3.]
 [ 0.  1.  2.  3.  4.]]


In practice string simularity is determined using the Levenshtein distance algorithm. This uses dynamic programming and is found in everything from spell check too detecting copyrighted information.

Note, there is no single formula for calculating a dynamic programming solution, instead there is just a common theme: use a grid and breakdown the problem into subproblems.

<h3>K-Nearest Neighbour</h3>
The principle of KNN is to classify a previously unclassified data or predict a value, based on other data with similar features. This is achieved by calculating the distance in euclidean space between what you're trying to classify/predict and its 'neaighbours', for which you already have the desired information.

So KNN can be used for the following tasks:
* Classification: grouping data based on previous information on 'similar' data
* Regression: predicting the value of some unknown variable based on information from 'similar' data

KNN is a machine learning algorithm. Ther e are many types of machine learning algorithms, some of which I have examples of in the DataQuest Projects repo that can be found on my github. For any machine learning algorithm, feature extraction, engineering, and chosing the correct features, is vital to successful predictions.

When performing machine learning tasks KNN is not always the ideal choice. KNN is best suited too simple problems with small datasets. It is a computationally expensive algorithm because for each query you need to calculate the euclidean distance to each training sample. Therefore, when using larger datasets it is best to use an algorithm that 'describes' the relationships that exist within the data itself. For this linear/logistic regression is helpful, as well as tree structures or graphs.

To see an example of KNN in action using the SciKit learn library please refer to this <a href="https://tinyurl.com/yc4vj6bk">notebook</a>

Other machine learning algorithms and examples in python can be found <a href="https://github.com/burtonbiomedical/DataQuest_Projects/tree/master/Machine%20Learning">here</a>. A huge thank you to www.dataquest.io for a comprehensive overview of machine learning with a project based approach, which is what I used to create the linked repo.

<h2>Advanced Topics</h2>
The final chapter of the Mannings Algorithms book covers 10 more advance algorithms, and is a very interesting read, but it doesn't provide any in-depth descritions. Below are some resources for the topics covered in this chapter:
* Trees:
    * <a href="https://www.youtube.com/watch?v=qH6yxkw0u78">Introduction to trees</a>
    * <a href="http://btechsmartclass.com/DS/U5_T3.html">B-Trees</a>
    * <a href="https://www.tutorialspoint.com/data_structures_algorithms/heap_data_structure.htm">Heaps</a>
* <a href="https://betterexplained.com/articles/an-interactive-guide-to-the-fourier-transform/">The Fourier Transform</a>
* MapReduce: this is an example of parallel programming that allows for distributed computing. I have personally only had exposure to Apache Spark when it comes to distributed computing, and a good tutorial to get started with the python API for Apache Spark can be found <a href="https://www.dezyre.com/apache-spark-tutorial/pyspark-tutorial">here.</a> The map and reduce functions have implementations in python however, demonstrated below:

In [83]:
array_one = [2,3,5,6,3,6,3]
array_two = list(map(lambda x: 3*x, array_one))
print(array_two)

[6, 9, 15, 18, 9, 18, 9]


In [88]:
from functools import reduce
reduced = reduce(lambda x,y: x*y, array_one)
print(reduced)

9720


* Probabilistic algorithms    
    * <a href="https://www.youtube.com/watch?v=U8Ni1yJ8ZS4">Bloom Filter</a>
    * <a href="https://www.youtube.com/watch?v=ZRCLZ3aIaVU">HyperLogLog</a>
* <a href="http://www.pythoncentral.io/hashing-strings-with-python/">Hashing Algorithms in Python</a>
* Linear Programming
    * <a href="https://www.analyticsvidhya.com/blog/2017/02/lintroductory-guide-on-linear-programming-explained-in-simple-english/">Introduction</a>
    * <a href="http://benalexkeen.com/linear-programming-with-python-and-pulp/">Linear Programming in Python</a>

And finally, two just incredible resources:
* https://betterexplained.com/archives/
* https://www.tutorialspoint.com/data_structures_algorithms/index.htm